name: Docker
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run pipeline
        run: |
            docker build . --file dockerfile -t toba44/jenkins_iti:v1.10
            docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker push toba44/jenkins_iti:v1.10
